config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about", to: "pages#about"
  
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    
    def index  
       @todos = Todo.all 
    end
    
    def new
        
        @todo = Todo.new
    end
    
    def create
        @todo = Todo.new(todo_params)
        if @todo.save 
            flash[:notice] = "Create todo successfully"
            redirect_to todo_path(@todo)
        else
            render 'new'
        end
    end
    
    def show
        @todo = Todo.find(params[:id])
    end
    
    def edit
        @todo = Todo.find(params[:id])
    end
    
    def update 
        @todo = Todo.find(params[:id])
        if @todo.update(todo_params)
            flash[:notice] = "Update todo successfully"
            redirect_to todo_path(@todo)
        else
            render 'edit'
        end
    end
    
    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        flash[:notice] = "Delete todo successfully"
        redirect_to todos_path
    end
    
    private
        def todo_params
           params.require(:todo).permit(:name, :description) 
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% flash.each do |name, msg| %>
      
        <h2><%= msg %></h2>
        
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Hi</h2>

app/views/todos/edit.html.erb
<% if @todo.errors.any? %>
    <h2>Can't create to do</h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg|%>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>
<%= form_for @todo do |f| %>
    <p> 
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, size: "50x6" %>
    </p>
    
    <p>
        <%= f.submit "Edit" %>
    </p>
<% end %>

app/views/todos/index.html.erb
<%= link_to "create new todo", new_todo_path %>
<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @todos.each do |todo| %>
    <tr>
        <td><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td><%= link_to "edit", edit_todo_path(todo) %></td>
        <td><%= link_to "show", todo_path(todo) %></td>
        <td><%= link_to "delete", todo_path(todo), method: :delete, data: {confirm: "are you sure?"} %></td>
    </tr>
    <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create new todo</h1>

<% if @todo.errors.any? %>
    <h2>Can't create to do</h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg|%>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <p> 
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, size: "50x6" %>
    </p>
    
    <p>
        <%= f.submit "Create" %>
    </p>
<% end %>

app/views/todos/show.html.erb
<h2>Showing todo</h2>

<p>
    Name: <%= @todo.name %>
</p>

<p>
    Description: <%= @todo.description %>
</p>

<%= link_to "edit", edit_todo_path(@todo) %>
<%= link_to "back to listing", todos_path %>